# Use the official Python 3.7 image
FROM python:3.7

# Install Tesseract OCR
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    tesseract-ocr-fra # (optional - for French language support)

# Set the working directory in the container
WORKDIR /app

# Copy the application code into the container
COPY . /app

# Copy the requirements file to the working directory
COPY requirements.txt requirements.txt

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000
EXPOSE 5000